=== ARM-software/data/schemas/pmu-schema.json
{
    "$schema": "http://json-schema.org/schema#",    
    "title": "CPU hardware event list",   
    "type": "object",
    "properties": {
        "_type": {
            "type": "string",
            "enum": ["Events"] 
        },
        "timestamp": {
            "description": "Time this description file was generated",
            "type": "string"
        },
        "refs": {
            "description": "Reference to documentation of these events",
            "type": "array",
            "items": {
                "title": "ref",
                "type": "object",
                "properties": {
                    "ref": {
                        "description": "Title of the document in which these event(s) are described",
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    },
                    "public": {
                        "description": "true if the document is publicly available",
                        "type": "boolean",
                        "default": false
                    }
                },
                "required": ["ref"]
            }
        },
        "implementer": {
            "description": "CPU implementer code, e.g. A for ARM Ltd.",
            "type": "string",
            "minLength": 1,
            "maxLength": 1
        },
        "architecture": {
            "description": "ARM architecture version, e.g. armv8",
            "type": "string",
            "pattern": "^armv"
        },
        "pmu_architecture": {
            "description": "ARM PMU architecture version, e.g. pmuv3",
            "type": "string",
            "pattern": "^pmu"
        },
        "cpu": {
            "description": "CPU name, e.g. Cortex-A7",
            "type": "string"
        },
        "cpuid": {
            "description": "CPU id, 5 or 6 hex digits",
            "type": "string"
        },
        "cpuids": {
            "description": "list of CPU ids",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "counters": {
            "description": "Number of physical hardware counters (e.g. 4, 6)",
            "type": "integer",
            "maximum": 31
        },
        "events": {
            "description": "The list of PMU events",
            "type": "array",
            "items": {
                "title": "Event",
                "type": "object",
                "properties": {
                    "refs": {
                        "description": "List of references for this event",
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    },
                    "code": {
                        "description": "The unique code to be programmed into the PMU event type register",
                        "type": "integer"
                    },
                    "name": {
                        "description": "Short mnemonic name",
                        "type": "string",
                        "pattern": "^[A-Z][A-Z_0-9]+$"
                    },
                    "trm_name": {
                        "description": "Mnemonic name from CPU Technical Reference Manual, where different",
                        "type": "string",
                        "pattern": "^[A-Z][A-Z_0-9]+$"
                    },
                    "description": {
                        "description": "Free-form English text description of the hardware event",
                        "type": "string"
                    },
                    "type": {
                        "description": "Classifies the event",
                        "type": "string",
                        "enum": ["INS", "CYCLE", "EXC", "UEVT", "ETM"]
                    },
                    "subtype": {
                        "description": "Sub-classification of the event",
                        "type": "string"
                    },
                    "architectural": {
                        "description": "True if this event is architectural, i.e. uarch-independent",
                        "type": "boolean",
                        "default": false
                    },
                    "for_driver": {
                        "description": "True if this event is for internal use by a PMU driver (e.g. CHAIN)",
                        "type": "boolean",
                        "default": false
                    },
                    "component": {
                        "description": "For non-architectural events, the microarchitecture component",
                        "type": "string"
                    },
                    "impdef": {
                        "description": "True if this event is implementation-defined",
                        "type": "boolean",
                        "default": false
                    },
                    "recommended": {
                        "description": "True if this event is implementation-defined and recommended",
                        "type": "boolean",
                        "default": false
                    },
                    "public": {
                        "description": "True if this event is publicly documented",
                        "type": "boolean",
                        "default": true
                    },
                    "revisionFrom": {
                        "description": "Revision in which this event was introduced",
                        "type": "integer"
                    },
                    "maximum": {
                        "description": "Maximum event count per cycle",
                        "type": "integer",
                        "minimum": 1
                    },
                    "hdl_path": {
                        "description": "Signal path in design source",
                        "type": "string"
                    },
                    "spe_index": {
                        "description": "Index of event in SPE event packet",
                        "type": "integer"
                    },
                    "event_bits": {
                        "description": "Number of bits on event bus",
                        "type": "integer"
                    },
                    "event_lsb": {
                        "description": "LSB position on PMUEVENTx event bus",
                        "type": "integer"
                    },
                    "trace_lsb": {
                        "description": "LSB position on CPU-to-ETM event bus",
                        "type": "integer"
                    },
                    "errevent_lsb": {
                        "description": "LSB position on ERREVENTx event bus",
                        "type": "integer"
                    }
                },
                "required": ["description"],
                "additionalProperties": false
            }
        }
    },
    "required": ["_type", "architecture", "events"],
    "additionalProperties": false
}

=== ARM-software/data/pmu/arm1136jf-s.json
{
    "_type": "Events",
    "timestamp": "Thu Oct 13 15:11:57 2022",
    "implementer": "A",
    "cpuid": "0x41b36",
    "cpu": "ARM1136JF-S",
    "architecture": "armv6",
    "refs": [
        {
            "ref": "gator events-ARM11.xml",
            "url": "https://raw.githubusercontent.com/ARM-software/gator/master/daemon/events-ARM11.xml",
            "public": true
        }
    ],
    "events": [
        {
            "code": 0,
            "refs": [
                0
            ],
            "architectural": false,
            "type": "INS",
            "description": "Instruction cache miss to a cacheable location, which requires a fetch from external memory"
        },
        {
            "code": 1,
            "refs": [
                0
            ],
            "architectural": false,
            "type": "INS",
            "description": "Stall because instruction buffer cannot deliver an instruction"
        },
        {
            "code": 2,
            "refs": [
                0
            ],
            "architectural": false,
            "type": "UEVT",
            "description": "Stall because of a data dependency"
        },
        {
            "code": 3,
            "refs": [
                0
            ],
            "architectural": false,
            "type": "INS",
            "description": "Instruction MicroTLB miss (unused on ARM1156)"
        },
        {
            "code": 4,
            "refs": [
                0
            ],
            "architectural": false,
            "type": "UEVT",
            "description": "Data MicroTLB miss (unused on ARM1156)"
        },
        {
            "code": 5,
            "refs": [
                0
            ],
            "type": "INS",
            "description": "Branch instruction executed, branch might or might not have changed program flow"
        },
        {
            "code": 6,
            "refs": [
                0
            ],
            "type": "UEVT",
            "component": "BPU",
            "description": "Branch mis-predicted"
        },
        {
            "code": 7,
            "refs": [
                0
            ],
            "type": "INS",
            "description": "Instructions executed"
        },
        {
            "code": 9,
            "refs": [
                0
            ],
            "architectural": false,
            "type": "UEVT",
            "subtype": "ACCESS",
            "description": "Data cache access, not including Cache operations"
        },
        {
            "code": 10,
            "refs": [
                0
            ],
            "architectural": false,
            "type": "UEVT",
            "subtype": "ACCESS",
            "description": "Data cache access, not including Cache Operations regardless of whether or not the location is cacheable"
        },
        {
            "code": 11,
            "refs": [
                0
            ],
            "architectural": false,
            "type": "UEVT",
            "description": "Data cache miss, not including Cache Operations"
        },
        {
            "code": 12,
            "refs": [
                0
            ],
            "architectural": false,
            "type": "UEVT",
            "subtype": "WRITE",
            "description": "Data cache write-back"
        },
        {
            "code": 13,
            "refs": [
                0
            ],
            "type": "UEVT",
            "description": "Software changed the PC"
        },
        {
            "code": 15,
            "refs": [
                0
            ],
            "architectural": false,
            "type": "UEVT",
            "description": "Main TLB miss (unused on ARM1156)"
        },
        {
            "code": 16,
            "refs": [
                0
            ],
            "type": "UEVT",
            "description": "Explicit external data or peripheral access"
        },
        {
            "code": 17,
            "refs": [
                0
            ],
            "architectural": false,
            "type": "UEVT",
            "description": "Stall because of Load Store Unit request queue being full"
        },
        {
            "code": 18,
            "refs": [
                0
            ],
            "type": "UEVT",
            "description": "The number of times the Write Buffer was drained because of a Data Synchronization Barrier command or Strongly Ordered operation"
        },
        {
            "code": 19,
            "refs": [
                0
            ],
            "architectural": false,
            "type": "CYCLE",
            "description": "The number of cycles which FIQ interrupts are disabled (ARM1156 only)"
        },
        {
            "code": 20,
            "refs": [
                0
            ],
            "architectural": false,
            "type": "CYCLE",
            "description": "The number of cycles which IRQ interrupts are disabled (ARM1156 only)"
        },
        {
            "code": 32,
            "refs": [
                0
            ],
            "architectural": false,
            "type": "ETM",
            "description": "ETMEXTOUT[0] signal was asserted for a cycle"
        },
        {
            "code": 33,
            "refs": [
                0
            ],
            "architectural": false,
            "type": "ETM",
            "description": "ETMEXTOUT[1] signal was asserted for a cycle"
        },
        {
            "code": 34,
            "refs": [
                0
            ],
            "type": "ETM",
            "description": "ETMEXTOUT[0] or ETMEXTOUT[1] was asserted"
        },
        {
            "code": 35,
            "refs": [
                0
            ],
            "type": "INS",
            "description": "Procedure call instruction executed"
        },
        {
            "code": 36,
            "refs": [
                0
            ],
            "type": "INS",
            "description": "Procedure return instruction executed"
        },
        {
            "code": 37,
            "refs": [
                0
            ],
            "type": "UEVT",
            "component": "BPU",
            "description": "Procedure return instruction executed and return address predicted"
        },
        {
            "code": 38,
            "refs": [
                0
            ],
            "type": "UEVT",
            "component": "BPU",
            "description": "Procedure return instruction executed and return address predicted incorrectly"
        },
        {
            "code": 48,
            "refs": [
                0
            ],
            "architectural": false,
            "type": "INS",
            "description": "Instruction cache Tag or Valid RAM parity error (ARM1156 only)"
        },
        {
            "code": 49,
            "refs": [
                0
            ],
            "architectural": false,
            "type": "INS",
            "description": "Instruction cache RAM parity error (ARM1156 only)"
        },
        {
            "code": 50,
            "refs": [
                0
            ],
            "architectural": false,
            "type": "UEVT",
            "description": "Data cache Tag or Valid RAM parity error (ARM1156 only)"
        },
        {
            "code": 51,
            "refs": [
                0
            ],
            "architectural": false,
            "type": "UEVT",
            "description": "Data cache RAM parity error (ARM1156 only)"
        },
        {
            "code": 52,
            "refs": [
                0
            ],
            "type": "UEVT",
            "description": "ITCM error (ARM1156 only)"
        },
        {
            "code": 53,
            "refs": [
                0
            ],
            "type": "UEVT",
            "description": "DTCM error (ARM1156 only)"
        },
        {
            "code": 54,
            "refs": [
                0
            ],
            "type": "UEVT",
            "description": "Procedure return address popped off the return stack (ARM1156 only)"
        },
        {
            "code": 55,
            "refs": [
                0
            ],
            "type": "UEVT",
            "component": "BPU",
            "description": "Procedure return address popped off the return stack has been incorrectly predicted by the PFU (ARM1156 only)"
        },
        {
            "code": 56,
            "refs": [
                0
            ],
            "architectural": false,
            "type": "UEVT",
            "description": "Data cache Dirty RAM parity error (ARM1156 only)"
        }
    ]
}
